FROM ubuntu:20.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=US/CT apt-get install -y curl software-properties-common lsb-release git wget vim sed binutils gawk bc time unzip gdb tree \
      make zlib1g-dev build-essential libtool autoconf gcc-8 g++-8 \
      libllvm-9-ocaml-dev libllvm9 llvm-9 llvm-9-dev llvm-9-doc llvm-9-examples llvm-9-runtime \
      clang-9 clang-tools-9 clang-9-doc libclang-common-9-dev libclang-9-dev libclang1-9 clang-format-9 python-clang-9 python3-pip clangd-9 \
      libboost-all-dev \
      libtbb-dev

RUN wget https://golang.org/dl/go1.16.3.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go1.16.3.linux-amd64.tar.gz

RUN apt-get remove --purge --auto-remove cmake \
    && wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - |  tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null \
    && apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" \
    && apt-get update \
    && apt-get install -y cmake

RUN apt-get clean -y

RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-9 10 \
    && update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-9 10

RUN pip3 install --upgrade pip && pip3 install numpy && pip3 install scipy && pip3 install matplotlib

RUN cd /usr/bin && ln -s /usr/bin/cmake cmake3

RUN echo 0 > /proc/sys/kernel/yama/ptrace_scope

RUN useradd --create-home --shell /bin/bash cgo23ae

ENV PATH=/usr/lib/llvm-9/bin/:$PATH
ENV PATH=/usr/local/go/bin/:$PATH
ENV LD_LIBRARY_PATH=/usr/lib/llvm-9/lib:$LD_LIBRARY_PATH
ENV LIBTBBSO=/usr/lib/x86_64-linux-gnu

USER cgo23ae
WORKDIR /home/cgo23ae

COPY --chown=cgo23ae ./LICENSE /home/cgo23ae/LICENSE
COPY --chown=cgo23ae ./README.md /home/cgo23ae/README.md
COPY --chown=cgo23ae ./bin /home/cgo23ae/bin
COPY --chown=cgo23ae ./results /home/cgo23ae/results
COPY --chown=cgo23ae ./benchmarkSuites /home/cgo23ae/benchmarkSuites

CMD /bin/bash
